name: "Release"

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      tag:
        type: "string"
        required: true

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-22.04"

    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Check out repository"
        id: "checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Dagger"
        id: "setup-dagger"
        uses: "camptocamp/setup-dagger@v1"
        with:
          cloud-token: "${{ secrets.DAGGER_CLOUD_TOKEN }}"

      - name: "Run Dagger"
        id: "run-dagger"
        run: "dagger call --version '${{ github.event_name == 'push' && github.ref || inputs.tag }}' release --github-token 'env:GITHUB_TOKEN'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
