name: "Release"

on:
  push:
    tags:
      - "v*"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-22.04"

    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Check out repository"
        id: "checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Dagger"
        id: "setup-dagger"
        uses: "camptocamp/setup-dagger@v1"

      - name: "Run Dagger"
        id: "run-dagger"
        run: "dagger call --version '${{ github.ref }}' release --github-token 'env:GITHUB_TOKEN'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
